name: "Meson build"
description: "Does a full build, test and installation"
inputs:
  path:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Prepare Build
      run: meson setup build ${{ inputs.path }}
      shell: bash
    - name: Run Build
      run: ninja -C build
      shell: bash
    - name: Run Test Suite
      run: meson test -C build
      shell: bash
    - name: Run Test Suite
      run: sudo meson install -C build
      shell: bash
    - name: Clean up build directory
      run: rm -rf build
      shell: bash
