name: Meson builds

on:
  workflow_call:
    inputs:
      cross:
        required: false
        type: boolean
      system:
        required: false
        type: string
      cpu_family:
        required: false
        type: string
      cpu:
        required: false
        type: string
      endian:
        required: false
        type: string
      prefix:
        required: false
        type: string
      package:
        required: false
        type: string

jobs:
  libcom-build:
    name: Meson build
    runs-on: ubuntu-latest
    env:
      CROSS: ${{ inputs.cross && 'true' }}
      HOST_SYSTEM: ${{ inputs.system }}
      HOST_CPU_FAMILY: ${{ inputs.cpu_family }}
      HOST_CPU: ${{ inputs.cpu }}
      HOST_ENDIAN: ${{ inputs.endian }}
      HOST_COMPILER_PREFIX: ${{ inputs.prefix }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: sudo apt-get install -y meson ninja-build pkg-config perl valgrind ${{ inputs.package }}

      - name: Build libCom
        run: ./.github/meson-build/build.sh modules/libcom
      - name: Build libCa
        run: ./.github/meson-build/build.sh modules/ca
      - name: Build pvData
        run: ./.github/meson-build/build.sh modules/pvData
      - name: Build normativeTypes
        run: ./.github/meson-build/build.sh modules/normativeTypes
      - name: Build pvAccess
        run: ./.github/meson-build/build.sh modules/pvAccess
      - name: Build pvDatabase
        run: ./.github/meson-build/build.sh modules/pvDatabase
