on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  meson-build:
    name: Meson build for ${{ inputs.path }}
    runs-on: ubuntu-latest
    steps:
      - run: "pushd ${{ inputs.path }}"
      - name: Prepare Build
        run: meson setup build
      - name: Run Build
        run: meson compile -v -C build
      - name: Run Test Suite
        run: meson test -v -C build
      - name: Run Test Suite
        run: meson install -v -C build
      - run: popd
