name: Meson builds

# on:
#   push:
#     paths-ignore:
#       - 'documentation/*'
#       - 'startup/*'
#       - '.appveyor/*'
#       - '.tools/*'
#       - '.lgtm.yml'
#       - '.gitattributes'
#       - '**/*.html'
#       - '**/*.md'
#   pull_request:
#     paths-ignore:
#       - 'documentation/*'
#       - 'startup/*'
#       - '.appveyor/*'
#       - '.tools/*'
#       - '.lgtm.yml'
#       - '.gitattributes'
#       - '**/*.html'
#       - '**/*.md'

on:
  workflow_call:
    inputs:
      cross:
        required: false
        type: boolean
      system:
        required: false
        type: string
      cpu_family:
        required: false
        type: string
      cpu:
        required: false
        type: string
      endian:
        required: false
        type: string
      prefix:
        required: false
        type: string
      package:
        required: false
        type: string


jobs:
  build:
    uses: ./.github/workflows/generic-full-meson-build.yml
    with:
      cross: true
      system: linux
      cpu_family: arm
      cpu: aarch64
      endian: little
      prefix: aarch64-linux-gnu-
      package: g++-aarch64-linux-gnu
    # strategy:
    #   matrix:
    #     target_arch:
    #       - cross: false
    #       - system: linux
    #         cpu_family: arm
    #         cpu: arm
    #         endian: little
    #         prefix: arm-linux-gnueabi-
    #       - system: linux
    #         cpu_family: arm
    #         cpu: arm
    #         endian: little
    #         prefix: arm-linux-gnueabihf-
    #       - system: linux
    #         cpu_family: arm
    #         cpu: aarch64
    #         endian: little
    #         prefix: aarch64-linux-
